### ISSUE TITLE
Not working with latest version of hyper 0.13, please update the dependencies

### ISSUE THREAD

**Issue by rousan** [abonander/multipart-async#18]

**Comment by koplas** [comment]
The master branch works on latest version of hyper 0.13, but the [crates.io](https://crates.io/crates/multipart-async) is outdated and doesn't work. @abonander please update the crates.io version.

**Comment by rousan** [comment]
I have made another implementation which is more flexible and gives more controls: https://github.com/rousan/multer-rs
