### ISSUE TITLE
question for RequestExt.

### ISSUE THREAD

**Issue by kiuma** [abonander/multipart-async#4]
Hello,
I was looking into your code and I've seen that RequestExt exports this method 

> fn into_multipart(self) -> Result<Self::Multipart, Self>;

I'm starting to use hyper and rust in general, but I immagined to use the api this way:

> request.into_multipart().and_then( _do_something_ }.then( _write_response_ )

Am I missing something? 
If this is the intended way of using the api, why this choice that seems little async way style ?

Kind regards,
Andrea

**Comment by july2993** [comment]
i try to use this to, it seems the version published is not ready for this method, i suppose you use version 0.0.2, you can check the code [https://docs.rs/crate/multipart-async/0.0.2/source/src/server/hyper.rs](here),  it does't impl RequestExt for hyper Request.

 but code in the master branch here seems has ready for hyper,  any way, i try to use the code in the git ,and it work for this method

 change the Cargo.toml like this
> [dependencies.multipart-async]
> version = "0.0"
> git = "https://github.com/abonander/multipart-async.git"

>

**Comment by kiuma** [comment]
Thanks, it works.

Il 09 nov 2017 7:45 AM, "Jiahao Huang" <notifications@github.com> ha
scritto:

i try to use this to, it seems the version published is not ready for this
method, i suppose you use version 0.0.2, you can check the code
https://docs.rs/crate/multipart-async/0.0.2/source/src/server/hyper.rs
<http://here>, it does't impl RequestExt for hyper Request.

but code in the master branch here seems has ready for hyper, any way, i
try to use the code in the git ,and it work for this method

change the Cargo.toml like this

[dependencies.multipart-async]
version = "0.0"
git = "https://github.com/abonander/multipart-async.git"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/abonander/multipart-async/issues/4#issuecomment-343062524>,
or mute the thread

**Comment by july2993** [comment]
well...i test on it, after get the Multipart, and call the wait method on it, it will hand hang for ever sometimes

**Comment by kiuma** [comment]
Ok I'll check it better. I'm writing my own hyper based web server. 
As soon as I'll handle the multipart suff I'll share my repo with you to double check

**Comment by abonander** [comment]
Sorry, I wasn't getting notifications for this repository for some reason. This crate isn't very well tested yet as it's still in development. For a while I was waiting on the Futures 0.2 refactor and then I got sidetracked with other projects as well as a new job. I'll probably be back to this in the coming weeks, though.
