### ISSUE TITLE
The trait bound `std::vec::Vec<u8>: std::convert::From<hyper::body::chunk::Chunk>` is not satisfied

### ISSUE THREAD

**Issue by paulzhang5511** [abonander/multipart-async#8]
![image](https://user-images.githubusercontent.com/53463972/64596022-ba6a2200-d3e5-11e9-8009-9115f9a2edf6.png)

**Comment by abonander** [comment]
`Chunk` is being removed from Hyper per my own request, in favor of using `bytes::Bytes`: https://github.com/hyperium/hyper/pull/1932#issuecomment-529516529

That will probably obviate this issue; however, note that `master` is not guaranteed to build right now as I'm still refactoring.

**Comment by abonander** [comment]
Fixed on latest master.
