### ISSUE TITLE
Support Rocket web framework.

### ISSUE THREAD

**Issue by paulzhang5511** [abonander/multipart-async#9]
The Rocket web framework supported async.
How to use it in the [Rocket web framework](https://github.com/SergioBenitez/Rocket/tree/async).

**Comment by abonander** [comment]
Async support is not released in Rocket yet. Based off previous discussions, I expect they're probably going to implement support for `multipart/form-data` themselves.

**Comment by paulzhang5511** [comment]
Can you write an example for supporting the rocket web framework?

**Comment by abonander** [comment]
I may once Rocket releases their async refactor; it doesn't make much sense to do it while they're still developing it.

**Comment by paulzhang5511** [comment]
The multipart-async is already very good. it is recommended release alpha first.

**Comment by DerNoob24** [comment]
is it already possible with the current state on the master branch? And could you explain how to do it?

**Comment by DerNoob24** [comment]
to answer my own question yes its possible with multer by rousan.
